server:
  port: 8080
spring:
  application:
    ###服务的名称
    name: mayikt-service
  datasource:
    username: mayikt
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.147.115:3306/mayikt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
logging:
  level:
    ###打印mybatis日志
    com.mayikt.mapper: debug
redis:
  host: 127.0.0.1
  port: 6379